import { Constants as C } from "@perksforu/app-core";
const { env } = process;

export default {
  PORT: env.PORT || 4001,
  ENVIRONMENT: env.NODE_ENV || C.Environment.DEVELOPMENT,
  SERVICE_NAME: env.SERVICE_NAME || "Notification Service",
  DB_CONNECTION_URL: env.DB_CONNECTION_URL || "",
  REDIS_URL: env.REDIS_URL || "",
  SENDGRID_API_KEY: env.SENDGRID_API_KEY,
  DEFAULT_SENDER_EMAIL: env.DEFAULT_SENDER_EMAIL || "",
  DEFAULT_SENDER_NAME: env.DEFAULT_SENDER_NAME || "",
  SECURITY_SCOPE_NAMESPACE: env.SECURITY_SCOPE_NAMESPACE || "notification",
  SERVICE_AUTH_ID: env.SERVICE_AUTH_ID || "",
  SERVICE_AUTH_SECRET: env.SERVICE_AUTH_SECRET || "",
  SERVICE_BASE_PATH: env.SERVICE_BASE_PATH || "",
  PUBSUB_TOPIC: env.CORE_PUBSUB_TOPIC_NAME || "",
  SECURITY_PUBLIC_KEY: env.SECURITY_PUBLIC_KEY || "",
  FIREBASE_SECURITY_KEYS: env.FIREBASE_SECURITY_KEYS || "",
  FIREBASE_PROJECT_ID: env.FIREBASE_PROJECT_ID || "",
  WEB_PUSH_DOMAIN_EMAIL: env.WEB_PUSH_DOMAIN_EMAIL || "",
  PUBLIC_VAPID_KEY: env.PUBLIC_VAPID_KEY || "",
  PRIVATE_VAPID_KEY: env.PRIVATE_VAPID_KEY || "",
};
